### ISSUE TITLE
official DDrace maps

### ISSUE THREAD

**Issue by Fisico** [DDRace/teeworlds#40]
include some good ddrace maps

xyz_ddrace
...

**Comment by Tsin** [comment]
dont add any maps that "exist" make a special contest for new ddrace maps

why not add old maps that are good :
because then many ppl will come and say add my map 
- why add his map and not add my map 

and in adding xyz 
why not add
koule, skynets, hardcore 
why not add LemonLand or any other map ?

to avoid  this kind of problems there should be made a special contest for official ddrace maps (and only the best mappers should JUDGE)

**Comment by Learath2** [comment]
Yes existing maps would be bad official maps for ddrace must be made for DDRace specially.

**Comment by GreYFoX** [comment]
i want a map that shows the features of DDRace not too hard for noobs but still not to easy
i want it to have teeish graphics, as much as i love and respect koule, it uses unteeish graphics. make something like nut server maps or xyz_ddrace2, don't use generic unhookable for hookable tiles ...
use common sense
the maps should be tested privately as it will be released to public for the first time with DDRace
further rules maybe added
if you are working on this email me @ greyfoxgti[("AT")]gmail.com so that i would know and test your map 
thanks

**Comment by Shahan** [comment]
I already suggested it here
http://ddrace.info/mybb/Thread-Official-Standart-DDRace-maps
But i failed with heinrich5991's answer. So 1 thing i can suggest is find really good mapper, who will create maps DDRace1, DDRace2, ..., DDRace_hardcore and so on. But only officially from DDRace community with love=)
