### ISSUE TITLE
Teleport 2 tee at same location at same time will stuck them

### ISSUE THREAD

**Issue by laxa** [DDRace/teeworlds#85]
Here are the test demo and the test map to show the bug.

http://L4x4t0r.free.fr/test.map
http://L4x4t0r.free.fr/test.demo

**Comment by JulianAssange** [comment]
this happened while doing a map with greyfox and me.. and some others, it eventally went away.. i havnt dl'd ur demo, but does it go away eventually?:

**Comment by laxa** [comment]
Yes.

**Comment by laxa** [comment]
Also happens when 2 people spec and unspec at same place and when 1 player switch to same team as another tee at same place...

**Comment by Learath2** [comment]
if you are in a one wide place in freeze its end of game

**Comment by GreYFoX** [comment]
This is a Teeworlds physics problems,  the way i see it, but it cannot be reproduced since they don't have teleporters, and they can't go into each other with speed now, so in result i see the ways to fix it are:
1- good mapping (more than 1 teleport to tile) + a proximity check in the code if a tee is already at the target use another teleporter! <--- somewhat honorable workaround
2- fix the physics <--- REAL FIX
3- detect when 2 tees are inside of each other an handle it <---- shameful workaround

I do not know how to do 2 because i have been away from the code for long.

maybe if @heinrich5991, @fisted, @eeeee or @ravomavain know they can tell me how they would do it and i can have a try when i am free or they can if they want
instead i can do 1 when i am free

**Comment by heinrich5991** [comment]
1) could be done like the teeworlds spawn, they already check it
2) fix the physics - either wait until release_date(matricks_bluesky), or be punished with prediction errors :/ Or write some good physics code and get it pulled into the main line.

**Comment by JulianAssange** [comment]
how do i stop these msgs emailing me? i want no part in anything tw's related nymore

**Comment by GreYFoX** [comment]
@heinrich5991 i know about 1 already i asked about 2 only!

and about your 2 it doesn't tell me how would it be done, i don't even remember which file to start at

**Comment by heinrich5991** [comment]
I only know the file to start with: [gamecore.cpp, line 434](https://github.com/GreYFoX/teeworlds/blob/DDRace/src/game/gamecore.cpp#L434)

**Comment by Shahan** [comment]
this bug appeared after "hammerfly fix" https://github.com/oy/teeworlds/commit/7db6d1e0567ee439e67c83a0ef670db9b419cfb6
so you can change physics back, and activate new collision only if 2 players have different pos Y

**Comment by GreYFoX** [comment]
I'll see what i can do

**Comment by laxa** [comment]
@greyfox: fixed !

**Comment by GreYFoX** [comment]
i came to close it, thanks @Laxa for closing it i am happy :)
