### ISSUE TITLE
limit

### ISSUE THREAD

**Issue by JulianAssange** [DDRace/teeworlds#94]
limit so you can only use /emote every 10 seconds.. also /eyeemote

**Comment by GreYFoX** [comment]
prove to me with this is important, the emoting with eyes doesn't pose risk or graphical pollution to people

if i am wrong correct me

**Comment by JulianAssange** [comment]
could cause lag and also makes the server log very big..

also it would make ddrace look more 'professional'

**Comment by JulianAssange** [comment]
when i say 'could' it does, someone released a bot that changes it every tick.. >.>

**Comment by alandball** [comment]
i have log file, of txt type, thats is 17 mb, just like Assange said. and thats just 1 logfile. Also, the real reason, is when im in console, via f2, and type status, it disappears almost immediately because of too much emote coming through. Usually results in me kicking sometimes good player because they have eyeemotebot

**Comment by heinrich5991** [comment]
well, kicking seems appropiate for having an bot that floods the server
